# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jekyll-IIIF Demo
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a demo of the Jekyll-IIIF plugin.
#baseurl: "/jekyll-iiif-demo" # the subpath of your site, e.g. /blog
baseurl: "/jekyll-iiif-gh"
url: "https://pbinkley.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pabinkley
github_username:  pbinkley

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-iiif
exclude:
  - Gemfile
  - Gemfile.lock

iiif_allowablefields:
  - label
  - description
  - attribution
  - logo

collections:
  narrenschiff:
    title: "Narrenschiff"
    output: true
    iiif: true
    paged: true
    fields:
      label: "Sebastian Brant, Aff-ghebeelde narren speel-schuyt, verciert met meer als hondert schoone figueren nae den aerdt van veelderley sotten die op aerden syn: bewesen met stichtelijcke exempelen, so uyt de H. Schrift als oock uyt de kerckelijcke oudt-vaders ende andere schrijvers meer, tot dienste van een yegelijcken"
      description: "Ghedruckt tot Leyden : By Henrick Lodewicxsz. van Haestens"
      attribution: "jekyll-iiif demo"
      logo: "logo.jpg"

  iiif_images:
    title: "Images"
    output: true
    iiif: true

defaults:
  - scope:
      path: ""
      type: iiif_collection
    values:
      layout: iiif_image

webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
